{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.fullname" . }}-backend
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" . | nindent 8 }}
        app: backend
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.backend.securityContext.runAsUser }}
        runAsGroup: {{ .Values.backend.securityContext.runAsGroup }}
        fsGroup: {{ .Values.backend.securityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.backend.securityContext.seccompProfile.type }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: HOME
              value: "/tmp"
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          envFrom:
            - secretRef:
                name: app-secrets
          volumeMounts:
            - name: backup-storage
              mountPath: /backups
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          ports:
            - containerPort: {{ .Values.backend.service.port }}
      volumes:
        - name: backup-storage
          persistentVolumeClaim:
            claimName: postgres-backups-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-backend
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
    app: backend
{{- end }}
