{{- if and .Values.observability.enabled .Values.observability.prometheus.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-prometheus-config
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app: prometheus
    component: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: "ecommerce-backend"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["{{ include "ecommerce.fullname" . }}-backend:8000"]
{{- end }}
