{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.fullname" . }}-worker
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "ecommerce.selectorLabels" . | nindent 6 }}
      app: worker
  template:
    metadata:
      labels:
        {{- include "ecommerce.selectorLabels" . | nindent 8 }}
        app: worker
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 102
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import redis; r = redis.from_url('redis://redis:6379'); r.ping()"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import redis; r = redis.from_url('redis://redis:6379'); r.ping()"
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- end }}
