apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-serve-config
data:
  serve.json: |
    {
      "TCP": {
        "80": {
          "TCPForward": "frontend.default.svc.cluster.local:80"
        },
        "3000": {
          "TCPForward": "grafana.default.svc.cluster.local:3000"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TS_AUTHKEY
                  optional: true
            - name: TS_HOSTNAME
              value: ecommerce-k8s
            - name: TS_USERSPACE
              value: "true"
            - name: TS_SERVE_CONFIG
              value: /config/serve.json
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: tailscale-serve-config
