apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  template:
    spec:
      enableServiceLinks: false
      containers:
      - name: migration
        image: ecommerce-backend:latest
        imagePullPolicy: IfNotPresent
        command: ["alembic", "upgrade", "head"]
        env:
        - name: POSTGRES_SERVER
          value: "postgres" # Connect directly to PG for migrations, not pgbouncer
        - name: POSTGRES_PORT
          value: "5432"
        envFrom:
        - secretRef:
            name: app-secrets
      restartPolicy: Never
  backoffLimit: 4
