"""sync_category_model

Revision ID: dd6e97f5a2a2
Revises: 0f49a0b717c6
Create Date: 2026-09-05 07:05:43.926175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6e97f5a2a2'
down_revision: Union[str, Sequence[str], None] = '0f49a0b717c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('province', sa.String(length=100), nullable=False))
    op.add_column('addresses', sa.Column('district', sa.String(length=100), nullable=False))
    op.add_column('addresses', sa.Column('ward', sa.String(length=100), nullable=False))
    op.add_column('addresses', sa.Column('street_detail', sa.String(length=255), nullable=False))
    op.add_column('addresses', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('addresses', 'city')
    op.drop_column('addresses', 'full_name')
    op.drop_column('addresses', 'country')
    op.drop_column('addresses', 'phone')
    op.drop_column('addresses', 'street_address')
    op.drop_column('addresses', 'state')
    op.drop_column('addresses', 'postal_code')
    op.add_column('categories', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('categories', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_unique_constraint(None, 'categories', ['slug'])
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.drop_column('categories', 'description')
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'address_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_address_id'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.add_column('payments', sa.Column('provider', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_unique_constraint(None, 'payments', ['order_id'])
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_order_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'amount')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'user_id')
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('payments', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'VND'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_order_id_fkey'), 'payments', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_column('payments', 'provider')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_address_id'), 'orders', 'addresses', ['address_id'], ['id'])
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.alter_column('orders', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'address_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    op.add_column('categories', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.drop_column('categories', 'parent_id')
    op.drop_column('categories', 'slug')
    op.add_column('addresses', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('street_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_user_id_fkey'), 'addresses', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.drop_column('addresses', 'phone_number')
    op.drop_column('addresses', 'street_detail')
    op.drop_column('addresses', 'ward')
    op.drop_column('addresses', 'district')
    op.drop_column('addresses', 'province')
    # ### end Alembic commands ###
